"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Info, AlertCircle } from "lucide-react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"

interface POINameInterpreterProps {
  verasetPoiId: string
  originalPoiId?: string | null
  jobId?: string
}

/**
 * Component to interpret and explain POI names from GeoJSON
 */
export function POINameInterpreter({ verasetPoiId, originalPoiId, jobId }: POINameInterpreterProps) {
  // Check if this is a Veraset auto-generated ID
  const isAutoGenerated = verasetPoiId.match(/^geo_radius_\d+$/)
  
  if (isAutoGenerated && !originalPoiId) {
    // Extract the index from geo_radius_X
    const match = verasetPoiId.match(/^geo_radius_(\d+)$/)
    const index = match ? parseInt(match[1]) : null
    
    return (
      <Alert>
        <AlertCircle className="h-4 w-4" />
        <AlertTitle>POI ID Interpretation</AlertTitle>
        <AlertDescription className="mt-2 space-y-2">
          <p>
            <strong>Veraset ID:</strong> <code className="font-mono">{verasetPoiId}</code>
          </p>
          {index !== null && (
            <p>
              This is an <strong>auto-generated ID</strong> created by Veraset API. The number <code>{index}</code> indicates 
              this is the <strong>{index + 1}{getOrdinalSuffix(index + 1)} POI</strong> in the array sent to Veraset.
            </p>
          )}
          <p className="text-sm text-muted-foreground">
            <strong>Why?</strong> Your GeoJSON features didn&apos;t include an <code>id</code> field or <code>properties.id</code>, 
            so Veraset generated sequential IDs based on the order in your POI array.
          </p>
          <p className="text-sm text-muted-foreground">
            <strong>To use custom names:</strong> Add an <code>id</code> field to each feature in your GeoJSON, 
            or include <code>properties.id</code> or <code>properties.name</code>.
          </p>
        </AlertDescription>
      </Alert>
    )
  }
  
  if (originalPoiId && originalPoiId !== verasetPoiId) {
    return (
      <Alert>
        <Info className="h-4 w-4" />
        <AlertTitle>POI ID Mapping</AlertTitle>
        <AlertDescription className="mt-2 space-y-2">
          <p>
            <strong>Original GeoJSON ID:</strong> <code className="font-mono">{originalPoiId}</code>
          </p>
          <p>
            <strong>Veraset ID:</strong> <code className="font-mono">{verasetPoiId}</code>
          </p>
          <p className="text-sm text-muted-foreground">
            This POI was identified in your GeoJSON as <code>{originalPoiId}</code>, but Veraset assigned it the ID <code>{verasetPoiId}</code> 
            for internal processing. The original name is preserved for reference.
          </p>
        </AlertDescription>
      </Alert>
    )
  }
  
  return null
}

function getOrdinalSuffix(n: number): string {
  const s = ["th", "st", "nd", "rd"]
  const v = n % 100
  return s[(v - 20) % 10] || s[v] || s[0]
}
